version: '3.8'

services:
  arm-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-backend
    environment:
      SERVER_VPS1_IP : ${SERVER_VPS1_IP:?error}
      USER_MARIADB : ${USER_MARIADB:?error}
      PWD_MARIADB : ${PWD_MARIADB:?error}
      ARM_VPS1_API_KEY : ${ARM_VPS1_API_KEY:?error}
    ports :
      - 8000:80 
    volumes : 
      - ./app:/api/app
    networks:
      - production-network
    labels:
      - traefik.http.routers.adminer.rule=PathPrefix(`/api-backend/`)


networks:
  production-network:
    name: production-network
    external: true