version: '3.8'

services:
  arm-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_VPS1_IP : ${SERVER_VPS1_IP:?error}
      USER_MARIADB : ${USER_MARIADB:?error}
      PWD_MARIADB : ${PWD_MARIADB:?error}
      ARM_VPS1_API_KEY : ${ARM_VPS1_API_KEY:?error}
    ports :
      - 8000:80 
    volumes : 
      - ./app:/api/app
    # Ajoutez d'autres configurations de service si nécessaire
