version: '3.8'

services:
  api-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-backend
    environment:
      SERVER_VPS1_IP : ${SERVER_VPS1_IP:?error}
      USER_MARIADB : ${USER_MARIADB:?error}
      PWD_MARIADB : ${PWD_MARIADB:?error}
      ARM_VPS1_API_KEY : ${ARM_VPS1_API_KEY:?error}
    ports :
      - 6001:6001
    volumes : 
      - ./app:/api/app
    networks:
      - production-network
    labels:
      - traefik.http.routers.api-backend.rule=PathPrefix(`/api-backend`)


networks:
  production-network:
    name: production-network
    external: true